version: "3.9"
services:
  postgres:
    image: postgres:15.3
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pg-admin
      POSTGRES_PASSWORD: pg-pass
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
