# Generated by Django 4.2.3 on 2024-01-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=1000)),
                ('release_date', models.DateField()),
                ('production_country', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('age_restriction', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(check=models.Q(('age_restriction__gt', 0)), name='age_restriction_positive'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('title',), name='movie_unq'),
        ),
    ]
