# Generated by Django 4.2.3 on 2024-01-06 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost_factor', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
            ],
            options={
                'db_table': 'halls',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.SmallIntegerField()),
                ('seat_number', models.SmallIntegerField()),
                ('cost_factor', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.hall')),
            ],
            options={
                'db_table': 'seats',
            },
        ),
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.CheckConstraint(check=models.Q(('cost_factor__gt', 0)), name='hall_cost_factor_positive'),
        ),
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.UniqueConstraint(fields=('name',), name='hall_unq'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.CheckConstraint(check=models.Q(('cost_factor__gt', 0)), name='seat_cost_factor_positive'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('hall_id', 'row_number', 'seat_number'), name='seat_unq'),
        ),
    ]
